#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCalendarAdmin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HealthCalendar")]
	public partial class HealthCalendarDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientID(ClientID instance);
    partial void UpdateClientID(ClientID instance);
    partial void DeleteClientID(ClientID instance);
    partial void InsertSubscriberActivity(SubscriberActivity instance);
    partial void UpdateSubscriberActivity(SubscriberActivity instance);
    partial void DeleteSubscriberActivity(SubscriberActivity instance);
    partial void InsertSubscriber(Subscriber instance);
    partial void UpdateSubscriber(Subscriber instance);
    partial void DeleteSubscriber(Subscriber instance);
    partial void InsertUnSubscribedActivity(UnSubscribedActivity instance);
    partial void UpdateUnSubscribedActivity(UnSubscribedActivity instance);
    partial void DeleteUnSubscribedActivity(UnSubscribedActivity instance);
    #endregion
		
		public HealthCalendarDataDataContext() : 
				base(global::HealthCalendarAdmin.Properties.Settings.Default.HealthCalendarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HealthCalendarDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthCalendarDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthCalendarDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthCalendarDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClientID> ClientIDs
		{
			get
			{
				return this.GetTable<ClientID>();
			}
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<SubscriberActivity> SubscriberActivities
		{
			get
			{
				return this.GetTable<SubscriberActivity>();
			}
		}
		
		public System.Data.Linq.Table<Subscriber> Subscribers
		{
			get
			{
				return this.GetTable<Subscriber>();
			}
		}
		
		public System.Data.Linq.Table<UnSubscribedActivity> UnSubscribedActivities
		{
			get
			{
				return this.GetTable<UnSubscribedActivity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientID")]
	public partial class ClientID : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _oathidID;
		
		private string _oAuthType;
		
		private string _client_id;
		
		private string _project_id;
		
		private string _auth_uri;
		
		private string _token_uri;
		
		private string _auth_provider_x509_cert_url;
		
		private string _client_secret;
		
		private string _client_secret2;
		
		private string _full_key;
		
		private string _OrganisationCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnoathidIDChanging(long value);
    partial void OnoathidIDChanged();
    partial void OnoAuthTypeChanging(string value);
    partial void OnoAuthTypeChanged();
    partial void Onclient_idChanging(string value);
    partial void Onclient_idChanged();
    partial void Onproject_idChanging(string value);
    partial void Onproject_idChanged();
    partial void Onauth_uriChanging(string value);
    partial void Onauth_uriChanged();
    partial void Ontoken_uriChanging(string value);
    partial void Ontoken_uriChanged();
    partial void Onauth_provider_x509_cert_urlChanging(string value);
    partial void Onauth_provider_x509_cert_urlChanged();
    partial void Onclient_secretChanging(string value);
    partial void Onclient_secretChanged();
    partial void Onclient_secret2Changing(string value);
    partial void Onclient_secret2Changed();
    partial void Onfull_keyChanging(string value);
    partial void Onfull_keyChanged();
    partial void OnOrganisationCodeChanging(string value);
    partial void OnOrganisationCodeChanged();
    #endregion
		
		public ClientID()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oathidID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long oathidID
		{
			get
			{
				return this._oathidID;
			}
			set
			{
				if ((this._oathidID != value))
				{
					this.OnoathidIDChanging(value);
					this.SendPropertyChanging();
					this._oathidID = value;
					this.SendPropertyChanged("oathidID");
					this.OnoathidIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oAuthType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string oAuthType
		{
			get
			{
				return this._oAuthType;
			}
			set
			{
				if ((this._oAuthType != value))
				{
					this.OnoAuthTypeChanging(value);
					this.SendPropertyChanging();
					this._oAuthType = value;
					this.SendPropertyChanged("oAuthType");
					this.OnoAuthTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="NVarChar(100)")]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this.Onclient_idChanging(value);
					this.SendPropertyChanging();
					this._client_id = value;
					this.SendPropertyChanged("client_id");
					this.Onclient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_id", DbType="NVarChar(30)")]
		public string project_id
		{
			get
			{
				return this._project_id;
			}
			set
			{
				if ((this._project_id != value))
				{
					this.Onproject_idChanging(value);
					this.SendPropertyChanging();
					this._project_id = value;
					this.SendPropertyChanged("project_id");
					this.Onproject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_uri", DbType="NVarChar(50)")]
		public string auth_uri
		{
			get
			{
				return this._auth_uri;
			}
			set
			{
				if ((this._auth_uri != value))
				{
					this.Onauth_uriChanging(value);
					this.SendPropertyChanging();
					this._auth_uri = value;
					this.SendPropertyChanged("auth_uri");
					this.Onauth_uriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token_uri", DbType="NVarChar(50)")]
		public string token_uri
		{
			get
			{
				return this._token_uri;
			}
			set
			{
				if ((this._token_uri != value))
				{
					this.Ontoken_uriChanging(value);
					this.SendPropertyChanging();
					this._token_uri = value;
					this.SendPropertyChanged("token_uri");
					this.Ontoken_uriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_provider_x509_cert_url", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string auth_provider_x509_cert_url
		{
			get
			{
				return this._auth_provider_x509_cert_url;
			}
			set
			{
				if ((this._auth_provider_x509_cert_url != value))
				{
					this.Onauth_provider_x509_cert_urlChanging(value);
					this.SendPropertyChanging();
					this._auth_provider_x509_cert_url = value;
					this.SendPropertyChanged("auth_provider_x509_cert_url");
					this.Onauth_provider_x509_cert_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_secret", DbType="NVarChar(50)")]
		public string client_secret
		{
			get
			{
				return this._client_secret;
			}
			set
			{
				if ((this._client_secret != value))
				{
					this.Onclient_secretChanging(value);
					this.SendPropertyChanging();
					this._client_secret = value;
					this.SendPropertyChanged("client_secret");
					this.Onclient_secretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_secret2", DbType="NVarChar(50)")]
		public string client_secret2
		{
			get
			{
				return this._client_secret2;
			}
			set
			{
				if ((this._client_secret2 != value))
				{
					this.Onclient_secret2Changing(value);
					this.SendPropertyChanging();
					this._client_secret2 = value;
					this.SendPropertyChanged("client_secret2");
					this.Onclient_secret2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_key", DbType="NVarChar(600)")]
		public string full_key
		{
			get
			{
				return this._full_key;
			}
			set
			{
				if ((this._full_key != value))
				{
					this.Onfull_keyChanging(value);
					this.SendPropertyChanging();
					this._full_key = value;
					this.SendPropertyChanged("full_key");
					this.Onfull_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganisationCode", DbType="NChar(4)")]
		public string OrganisationCode
		{
			get
			{
				return this._OrganisationCode;
			}
			set
			{
				if ((this._OrganisationCode != value))
				{
					this.OnOrganisationCodeChanging(value);
					this.SendPropertyChanging();
					this._OrganisationCode = value;
					this.SendPropertyChanged("OrganisationCode");
					this.OnOrganisationCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	public partial class Setting
	{
		
		private string _TimeZone;
		
		private string _OrganisationName;
		
		private string _OrganisationCode;
		
		private string _OrgLocation;
		
		private System.Nullable<bool> _GoogleEnabled;
		
		private System.Xml.Linq.XElement _GoogleCredentials;
		
		private string _GoogleMasterAccount;
		
		private System.Nullable<bool> _OutlookEnabled;
		
		private System.Xml.Linq.XElement _OutlookCredentials;
		
		private string _OutlookMaterAccount;
		
		private System.Nullable<bool> _ExchangeEnabled;
		
		private string _ExchangeExchangeServer;
		
		private string _ExchangeCredentials;
		
		private string _ExchangeMasterAccount;
		
		private string _ExchangeDisplayName;
		
		private string _ExchangeFQDN;
		
		private string _ExchangeUserDN;
		
		private System.Nullable<bool> _NHSNetEnabled;
		
		private string _NHSNetExchangeServer;
		
		private string _NHSNetCredentials;
		
		private string _NHSNetMasterAccount;
		
		private string _NHSNetDisplayName;
		
		private string _NHSNetFQDN;
		
		private string _NHSNetUserDN;
		
		public Setting()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganisationName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string OrganisationName
		{
			get
			{
				return this._OrganisationName;
			}
			set
			{
				if ((this._OrganisationName != value))
				{
					this._OrganisationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganisationCode", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string OrganisationCode
		{
			get
			{
				return this._OrganisationCode;
			}
			set
			{
				if ((this._OrganisationCode != value))
				{
					this._OrganisationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgLocation", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string OrgLocation
		{
			get
			{
				return this._OrgLocation;
			}
			set
			{
				if ((this._OrgLocation != value))
				{
					this._OrgLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleEnabled", DbType="Bit")]
		public System.Nullable<bool> GoogleEnabled
		{
			get
			{
				return this._GoogleEnabled;
			}
			set
			{
				if ((this._GoogleEnabled != value))
				{
					this._GoogleEnabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleCredentials", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement GoogleCredentials
		{
			get
			{
				return this._GoogleCredentials;
			}
			set
			{
				if ((this._GoogleCredentials != value))
				{
					this._GoogleCredentials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleMasterAccount", DbType="NVarChar(MAX)")]
		public string GoogleMasterAccount
		{
			get
			{
				return this._GoogleMasterAccount;
			}
			set
			{
				if ((this._GoogleMasterAccount != value))
				{
					this._GoogleMasterAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutlookEnabled", DbType="Bit")]
		public System.Nullable<bool> OutlookEnabled
		{
			get
			{
				return this._OutlookEnabled;
			}
			set
			{
				if ((this._OutlookEnabled != value))
				{
					this._OutlookEnabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutlookCredentials", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement OutlookCredentials
		{
			get
			{
				return this._OutlookCredentials;
			}
			set
			{
				if ((this._OutlookCredentials != value))
				{
					this._OutlookCredentials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutlookMaterAccount", DbType="NVarChar(MAX)")]
		public string OutlookMaterAccount
		{
			get
			{
				return this._OutlookMaterAccount;
			}
			set
			{
				if ((this._OutlookMaterAccount != value))
				{
					this._OutlookMaterAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeEnabled", DbType="Bit")]
		public System.Nullable<bool> ExchangeEnabled
		{
			get
			{
				return this._ExchangeEnabled;
			}
			set
			{
				if ((this._ExchangeEnabled != value))
				{
					this._ExchangeEnabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeExchangeServer", DbType="NVarChar(MAX)")]
		public string ExchangeExchangeServer
		{
			get
			{
				return this._ExchangeExchangeServer;
			}
			set
			{
				if ((this._ExchangeExchangeServer != value))
				{
					this._ExchangeExchangeServer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeCredentials", DbType="NVarChar(MAX)")]
		public string ExchangeCredentials
		{
			get
			{
				return this._ExchangeCredentials;
			}
			set
			{
				if ((this._ExchangeCredentials != value))
				{
					this._ExchangeCredentials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeMasterAccount", DbType="NVarChar(MAX)")]
		public string ExchangeMasterAccount
		{
			get
			{
				return this._ExchangeMasterAccount;
			}
			set
			{
				if ((this._ExchangeMasterAccount != value))
				{
					this._ExchangeMasterAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeDisplayName", DbType="NVarChar(MAX)")]
		public string ExchangeDisplayName
		{
			get
			{
				return this._ExchangeDisplayName;
			}
			set
			{
				if ((this._ExchangeDisplayName != value))
				{
					this._ExchangeDisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeFQDN", DbType="NVarChar(MAX)")]
		public string ExchangeFQDN
		{
			get
			{
				return this._ExchangeFQDN;
			}
			set
			{
				if ((this._ExchangeFQDN != value))
				{
					this._ExchangeFQDN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeUserDN", DbType="NVarChar(MAX)")]
		public string ExchangeUserDN
		{
			get
			{
				return this._ExchangeUserDN;
			}
			set
			{
				if ((this._ExchangeUserDN != value))
				{
					this._ExchangeUserDN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetEnabled", DbType="Bit")]
		public System.Nullable<bool> NHSNetEnabled
		{
			get
			{
				return this._NHSNetEnabled;
			}
			set
			{
				if ((this._NHSNetEnabled != value))
				{
					this._NHSNetEnabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetExchangeServer", DbType="NVarChar(MAX)")]
		public string NHSNetExchangeServer
		{
			get
			{
				return this._NHSNetExchangeServer;
			}
			set
			{
				if ((this._NHSNetExchangeServer != value))
				{
					this._NHSNetExchangeServer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetCredentials", DbType="NVarChar(MAX)")]
		public string NHSNetCredentials
		{
			get
			{
				return this._NHSNetCredentials;
			}
			set
			{
				if ((this._NHSNetCredentials != value))
				{
					this._NHSNetCredentials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetMasterAccount", DbType="NVarChar(MAX)")]
		public string NHSNetMasterAccount
		{
			get
			{
				return this._NHSNetMasterAccount;
			}
			set
			{
				if ((this._NHSNetMasterAccount != value))
				{
					this._NHSNetMasterAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetDisplayName", DbType="NVarChar(MAX)")]
		public string NHSNetDisplayName
		{
			get
			{
				return this._NHSNetDisplayName;
			}
			set
			{
				if ((this._NHSNetDisplayName != value))
				{
					this._NHSNetDisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetFQDN", DbType="NVarChar(MAX)")]
		public string NHSNetFQDN
		{
			get
			{
				return this._NHSNetFQDN;
			}
			set
			{
				if ((this._NHSNetFQDN != value))
				{
					this._NHSNetFQDN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetUserDN", DbType="NVarChar(MAX)")]
		public string NHSNetUserDN
		{
			get
			{
				return this._NHSNetUserDN;
			}
			set
			{
				if ((this._NHSNetUserDN != value))
				{
					this._NHSNetUserDN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubscriberActivity")]
	public partial class SubscriberActivity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PrimaryID;
		
		private System.Nullable<decimal> _SubscriberID;
		
		private string _SubscriberUID;
		
		private string _ActivityType;
		
		private string _EventSummary;
		
		private string _EventLocation;
		
		private string _EventDescription;
		
		private System.DateTime _EventStart;
		
		private System.Nullable<System.DateTime> _EventEnd;
		
		private EntityRef<Subscriber> _Subscriber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrimaryIDChanging(long value);
    partial void OnPrimaryIDChanged();
    partial void OnSubscriberIDChanging(System.Nullable<decimal> value);
    partial void OnSubscriberIDChanged();
    partial void OnSubscriberUIDChanging(string value);
    partial void OnSubscriberUIDChanged();
    partial void OnActivityTypeChanging(string value);
    partial void OnActivityTypeChanged();
    partial void OnEventSummaryChanging(string value);
    partial void OnEventSummaryChanged();
    partial void OnEventLocationChanging(string value);
    partial void OnEventLocationChanged();
    partial void OnEventDescriptionChanging(string value);
    partial void OnEventDescriptionChanged();
    partial void OnEventStartChanging(System.DateTime value);
    partial void OnEventStartChanged();
    partial void OnEventEndChanging(System.Nullable<System.DateTime> value);
    partial void OnEventEndChanged();
    #endregion
		
		public SubscriberActivity()
		{
			this._Subscriber = default(EntityRef<Subscriber>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PrimaryID
		{
			get
			{
				return this._PrimaryID;
			}
			set
			{
				if ((this._PrimaryID != value))
				{
					this.OnPrimaryIDChanging(value);
					this.SendPropertyChanging();
					this._PrimaryID = value;
					this.SendPropertyChanged("PrimaryID");
					this.OnPrimaryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberID", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> SubscriberID
		{
			get
			{
				return this._SubscriberID;
			}
			set
			{
				if ((this._SubscriberID != value))
				{
					if (this._Subscriber.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscriberIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberID = value;
					this.SendPropertyChanged("SubscriberID");
					this.OnSubscriberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberUID", DbType="NVarChar(20)")]
		public string SubscriberUID
		{
			get
			{
				return this._SubscriberUID;
			}
			set
			{
				if ((this._SubscriberUID != value))
				{
					this.OnSubscriberUIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberUID = value;
					this.SendPropertyChanged("SubscriberUID");
					this.OnSubscriberUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ActivityType
		{
			get
			{
				return this._ActivityType;
			}
			set
			{
				if ((this._ActivityType != value))
				{
					this.OnActivityTypeChanging(value);
					this.SendPropertyChanging();
					this._ActivityType = value;
					this.SendPropertyChanged("ActivityType");
					this.OnActivityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventSummary", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string EventSummary
		{
			get
			{
				return this._EventSummary;
			}
			set
			{
				if ((this._EventSummary != value))
				{
					this.OnEventSummaryChanging(value);
					this.SendPropertyChanging();
					this._EventSummary = value;
					this.SendPropertyChanged("EventSummary");
					this.OnEventSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventLocation", DbType="NVarChar(300)")]
		public string EventLocation
		{
			get
			{
				return this._EventLocation;
			}
			set
			{
				if ((this._EventLocation != value))
				{
					this.OnEventLocationChanging(value);
					this.SendPropertyChanging();
					this._EventLocation = value;
					this.SendPropertyChanged("EventLocation");
					this.OnEventLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDescription", DbType="NVarChar(600)")]
		public string EventDescription
		{
			get
			{
				return this._EventDescription;
			}
			set
			{
				if ((this._EventDescription != value))
				{
					this.OnEventDescriptionChanging(value);
					this.SendPropertyChanging();
					this._EventDescription = value;
					this.SendPropertyChanged("EventDescription");
					this.OnEventDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventStart", DbType="DateTime NOT NULL")]
		public System.DateTime EventStart
		{
			get
			{
				return this._EventStart;
			}
			set
			{
				if ((this._EventStart != value))
				{
					this.OnEventStartChanging(value);
					this.SendPropertyChanging();
					this._EventStart = value;
					this.SendPropertyChanged("EventStart");
					this.OnEventStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> EventEnd
		{
			get
			{
				return this._EventEnd;
			}
			set
			{
				if ((this._EventEnd != value))
				{
					this.OnEventEndChanging(value);
					this.SendPropertyChanging();
					this._EventEnd = value;
					this.SendPropertyChanged("EventEnd");
					this.OnEventEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscriber_SubscriberActivity", Storage="_Subscriber", ThisKey="SubscriberID", OtherKey="SubscriberID", IsForeignKey=true)]
		public Subscriber Subscriber
		{
			get
			{
				return this._Subscriber.Entity;
			}
			set
			{
				Subscriber previousValue = this._Subscriber.Entity;
				if (((previousValue != value) 
							|| (this._Subscriber.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscriber.Entity = null;
						previousValue.SubscriberActivities.Remove(this);
					}
					this._Subscriber.Entity = value;
					if ((value != null))
					{
						value.SubscriberActivities.Add(this);
						this._SubscriberID = value.SubscriberID;
					}
					else
					{
						this._SubscriberID = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("Subscriber");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subscribers")]
	public partial class Subscriber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _SubscriberID;
		
		private System.Nullable<decimal> _SubscriberOID;
		
		private string _Initials;
		
		private string _Title;
		
		private string _Firstname;
		
		private string _Surname;
		
		private string _Sex;
		
		private System.Nullable<System.DateTime> _ModifiedDTTM;
		
		private System.Nullable<System.DateTime> _EndDTTM;
		
		private string _Occupation;
		
		private string _MainIdentifier;
		
		private string _SourceOID;
		
		private string _SourceType;
		
		private string _OwnerOrganisationOID;
		
		private string _RONEOID;
		
		private string _UITYPCODE;
		
		private string _GoogleEmail;
		
		private string _GoogleCalendarID;
		
		private string _OutlookEmail;
		
		private string _OutlookCalendarID;
		
		private string _ExchangeEmail;
		
		private string _ExchangeCalendarID;
		
		private string _ExchangeCalendarName;
		
		private string _NHSNetEmail;
		
		private string _NHSNetCalendarID;
		
		private string _NHSNetCalendarName;
		
		private string _AppleEmail;
		
		private string _AppleCalendarID;
		
		private EntitySet<SubscriberActivity> _SubscriberActivities;
		
		private EntitySet<UnSubscribedActivity> _UnSubscribedActivities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubscriberIDChanging(decimal value);
    partial void OnSubscriberIDChanged();
    partial void OnSubscriberOIDChanging(System.Nullable<decimal> value);
    partial void OnSubscriberOIDChanged();
    partial void OnInitialsChanging(string value);
    partial void OnInitialsChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnModifiedDTTMChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDTTMChanged();
    partial void OnEndDTTMChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDTTMChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnMainIdentifierChanging(string value);
    partial void OnMainIdentifierChanged();
    partial void OnSourceOIDChanging(string value);
    partial void OnSourceOIDChanged();
    partial void OnSourceTypeChanging(string value);
    partial void OnSourceTypeChanged();
    partial void OnOwnerOrganisationOIDChanging(string value);
    partial void OnOwnerOrganisationOIDChanged();
    partial void OnRONEOIDChanging(string value);
    partial void OnRONEOIDChanged();
    partial void OnUITYPCODEChanging(string value);
    partial void OnUITYPCODEChanged();
    partial void OnGoogleEmailChanging(string value);
    partial void OnGoogleEmailChanged();
    partial void OnGoogleCalendarIDChanging(string value);
    partial void OnGoogleCalendarIDChanged();
    partial void OnOutlookEmailChanging(string value);
    partial void OnOutlookEmailChanged();
    partial void OnOutlookCalendarIDChanging(string value);
    partial void OnOutlookCalendarIDChanged();
    partial void OnExchangeEmailChanging(string value);
    partial void OnExchangeEmailChanged();
    partial void OnExchangeCalendarIDChanging(string value);
    partial void OnExchangeCalendarIDChanged();
    partial void OnExchangeCalendarNameChanging(string value);
    partial void OnExchangeCalendarNameChanged();
    partial void OnNHSNetEmailChanging(string value);
    partial void OnNHSNetEmailChanged();
    partial void OnNHSNetCalendarIDChanging(string value);
    partial void OnNHSNetCalendarIDChanged();
    partial void OnNHSNetCalendarNameChanging(string value);
    partial void OnNHSNetCalendarNameChanged();
    partial void OnAppleEmailChanging(string value);
    partial void OnAppleEmailChanged();
    partial void OnAppleCalendarIDChanging(string value);
    partial void OnAppleCalendarIDChanged();
    #endregion
		
		public Subscriber()
		{
			this._SubscriberActivities = new EntitySet<SubscriberActivity>(new Action<SubscriberActivity>(this.attach_SubscriberActivities), new Action<SubscriberActivity>(this.detach_SubscriberActivities));
			this._UnSubscribedActivities = new EntitySet<UnSubscribedActivity>(new Action<UnSubscribedActivity>(this.attach_UnSubscribedActivities), new Action<UnSubscribedActivity>(this.detach_UnSubscribedActivities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberID", AutoSync=AutoSync.OnInsert, DbType="Decimal(19,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal SubscriberID
		{
			get
			{
				return this._SubscriberID;
			}
			set
			{
				if ((this._SubscriberID != value))
				{
					this.OnSubscriberIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberID = value;
					this.SendPropertyChanged("SubscriberID");
					this.OnSubscriberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberOID", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> SubscriberOID
		{
			get
			{
				return this._SubscriberOID;
			}
			set
			{
				if ((this._SubscriberOID != value))
				{
					this.OnSubscriberOIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberOID = value;
					this.SendPropertyChanged("SubscriberOID");
					this.OnSubscriberOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Initials", DbType="NVarChar(MAX)")]
		public string Initials
		{
			get
			{
				return this._Initials;
			}
			set
			{
				if ((this._Initials != value))
				{
					this.OnInitialsChanging(value);
					this.SendPropertyChanging();
					this._Initials = value;
					this.SendPropertyChanged("Initials");
					this.OnInitialsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(MAX)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(MAX)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(MAX)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDTTM", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDTTM
		{
			get
			{
				return this._ModifiedDTTM;
			}
			set
			{
				if ((this._ModifiedDTTM != value))
				{
					this.OnModifiedDTTMChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDTTM = value;
					this.SendPropertyChanged("ModifiedDTTM");
					this.OnModifiedDTTMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDTTM", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDTTM
		{
			get
			{
				return this._EndDTTM;
			}
			set
			{
				if ((this._EndDTTM != value))
				{
					this.OnEndDTTMChanging(value);
					this.SendPropertyChanging();
					this._EndDTTM = value;
					this.SendPropertyChanged("EndDTTM");
					this.OnEndDTTMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="NVarChar(MAX)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainIdentifier", DbType="NVarChar(MAX)")]
		public string MainIdentifier
		{
			get
			{
				return this._MainIdentifier;
			}
			set
			{
				if ((this._MainIdentifier != value))
				{
					this.OnMainIdentifierChanging(value);
					this.SendPropertyChanging();
					this._MainIdentifier = value;
					this.SendPropertyChanged("MainIdentifier");
					this.OnMainIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceOID", DbType="NVarChar(MAX)")]
		public string SourceOID
		{
			get
			{
				return this._SourceOID;
			}
			set
			{
				if ((this._SourceOID != value))
				{
					this.OnSourceOIDChanging(value);
					this.SendPropertyChanging();
					this._SourceOID = value;
					this.SendPropertyChanged("SourceOID");
					this.OnSourceOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceType", DbType="NVarChar(MAX)")]
		public string SourceType
		{
			get
			{
				return this._SourceType;
			}
			set
			{
				if ((this._SourceType != value))
				{
					this.OnSourceTypeChanging(value);
					this.SendPropertyChanging();
					this._SourceType = value;
					this.SendPropertyChanged("SourceType");
					this.OnSourceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerOrganisationOID", DbType="NVarChar(MAX)")]
		public string OwnerOrganisationOID
		{
			get
			{
				return this._OwnerOrganisationOID;
			}
			set
			{
				if ((this._OwnerOrganisationOID != value))
				{
					this.OnOwnerOrganisationOIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerOrganisationOID = value;
					this.SendPropertyChanged("OwnerOrganisationOID");
					this.OnOwnerOrganisationOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RONEOID", DbType="NVarChar(MAX)")]
		public string RONEOID
		{
			get
			{
				return this._RONEOID;
			}
			set
			{
				if ((this._RONEOID != value))
				{
					this.OnRONEOIDChanging(value);
					this.SendPropertyChanging();
					this._RONEOID = value;
					this.SendPropertyChanged("RONEOID");
					this.OnRONEOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UITYPCODE", DbType="NVarChar(MAX)")]
		public string UITYPCODE
		{
			get
			{
				return this._UITYPCODE;
			}
			set
			{
				if ((this._UITYPCODE != value))
				{
					this.OnUITYPCODEChanging(value);
					this.SendPropertyChanging();
					this._UITYPCODE = value;
					this.SendPropertyChanged("UITYPCODE");
					this.OnUITYPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleEmail", DbType="NVarChar(MAX)")]
		public string GoogleEmail
		{
			get
			{
				return this._GoogleEmail;
			}
			set
			{
				if ((this._GoogleEmail != value))
				{
					this.OnGoogleEmailChanging(value);
					this.SendPropertyChanging();
					this._GoogleEmail = value;
					this.SendPropertyChanged("GoogleEmail");
					this.OnGoogleEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleCalendarID", DbType="NVarChar(MAX)")]
		public string GoogleCalendarID
		{
			get
			{
				return this._GoogleCalendarID;
			}
			set
			{
				if ((this._GoogleCalendarID != value))
				{
					this.OnGoogleCalendarIDChanging(value);
					this.SendPropertyChanging();
					this._GoogleCalendarID = value;
					this.SendPropertyChanged("GoogleCalendarID");
					this.OnGoogleCalendarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutlookEmail", DbType="NVarChar(MAX)")]
		public string OutlookEmail
		{
			get
			{
				return this._OutlookEmail;
			}
			set
			{
				if ((this._OutlookEmail != value))
				{
					this.OnOutlookEmailChanging(value);
					this.SendPropertyChanging();
					this._OutlookEmail = value;
					this.SendPropertyChanged("OutlookEmail");
					this.OnOutlookEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutlookCalendarID", DbType="NVarChar(MAX)")]
		public string OutlookCalendarID
		{
			get
			{
				return this._OutlookCalendarID;
			}
			set
			{
				if ((this._OutlookCalendarID != value))
				{
					this.OnOutlookCalendarIDChanging(value);
					this.SendPropertyChanging();
					this._OutlookCalendarID = value;
					this.SendPropertyChanged("OutlookCalendarID");
					this.OnOutlookCalendarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeEmail", DbType="NVarChar(MAX)")]
		public string ExchangeEmail
		{
			get
			{
				return this._ExchangeEmail;
			}
			set
			{
				if ((this._ExchangeEmail != value))
				{
					this.OnExchangeEmailChanging(value);
					this.SendPropertyChanging();
					this._ExchangeEmail = value;
					this.SendPropertyChanged("ExchangeEmail");
					this.OnExchangeEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeCalendarID", DbType="NVarChar(MAX)")]
		public string ExchangeCalendarID
		{
			get
			{
				return this._ExchangeCalendarID;
			}
			set
			{
				if ((this._ExchangeCalendarID != value))
				{
					this.OnExchangeCalendarIDChanging(value);
					this.SendPropertyChanging();
					this._ExchangeCalendarID = value;
					this.SendPropertyChanged("ExchangeCalendarID");
					this.OnExchangeCalendarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeCalendarName", DbType="NVarChar(MAX)")]
		public string ExchangeCalendarName
		{
			get
			{
				return this._ExchangeCalendarName;
			}
			set
			{
				if ((this._ExchangeCalendarName != value))
				{
					this.OnExchangeCalendarNameChanging(value);
					this.SendPropertyChanging();
					this._ExchangeCalendarName = value;
					this.SendPropertyChanged("ExchangeCalendarName");
					this.OnExchangeCalendarNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetEmail", DbType="NVarChar(MAX)")]
		public string NHSNetEmail
		{
			get
			{
				return this._NHSNetEmail;
			}
			set
			{
				if ((this._NHSNetEmail != value))
				{
					this.OnNHSNetEmailChanging(value);
					this.SendPropertyChanging();
					this._NHSNetEmail = value;
					this.SendPropertyChanged("NHSNetEmail");
					this.OnNHSNetEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetCalendarID", DbType="NVarChar(MAX)")]
		public string NHSNetCalendarID
		{
			get
			{
				return this._NHSNetCalendarID;
			}
			set
			{
				if ((this._NHSNetCalendarID != value))
				{
					this.OnNHSNetCalendarIDChanging(value);
					this.SendPropertyChanging();
					this._NHSNetCalendarID = value;
					this.SendPropertyChanged("NHSNetCalendarID");
					this.OnNHSNetCalendarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHSNetCalendarName", DbType="NVarChar(MAX)")]
		public string NHSNetCalendarName
		{
			get
			{
				return this._NHSNetCalendarName;
			}
			set
			{
				if ((this._NHSNetCalendarName != value))
				{
					this.OnNHSNetCalendarNameChanging(value);
					this.SendPropertyChanging();
					this._NHSNetCalendarName = value;
					this.SendPropertyChanged("NHSNetCalendarName");
					this.OnNHSNetCalendarNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppleEmail", DbType="NVarChar(MAX)")]
		public string AppleEmail
		{
			get
			{
				return this._AppleEmail;
			}
			set
			{
				if ((this._AppleEmail != value))
				{
					this.OnAppleEmailChanging(value);
					this.SendPropertyChanging();
					this._AppleEmail = value;
					this.SendPropertyChanged("AppleEmail");
					this.OnAppleEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppleCalendarID", DbType="NVarChar(MAX)")]
		public string AppleCalendarID
		{
			get
			{
				return this._AppleCalendarID;
			}
			set
			{
				if ((this._AppleCalendarID != value))
				{
					this.OnAppleCalendarIDChanging(value);
					this.SendPropertyChanging();
					this._AppleCalendarID = value;
					this.SendPropertyChanged("AppleCalendarID");
					this.OnAppleCalendarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscriber_SubscriberActivity", Storage="_SubscriberActivities", ThisKey="SubscriberID", OtherKey="SubscriberID")]
		public EntitySet<SubscriberActivity> SubscriberActivities
		{
			get
			{
				return this._SubscriberActivities;
			}
			set
			{
				this._SubscriberActivities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscriber_UnSubscribedActivity", Storage="_UnSubscribedActivities", ThisKey="SubscriberID", OtherKey="SubscriberID")]
		public EntitySet<UnSubscribedActivity> UnSubscribedActivities
		{
			get
			{
				return this._UnSubscribedActivities;
			}
			set
			{
				this._UnSubscribedActivities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubscriberActivities(SubscriberActivity entity)
		{
			this.SendPropertyChanging();
			entity.Subscriber = this;
		}
		
		private void detach_SubscriberActivities(SubscriberActivity entity)
		{
			this.SendPropertyChanging();
			entity.Subscriber = null;
		}
		
		private void attach_UnSubscribedActivities(UnSubscribedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Subscriber = this;
		}
		
		private void detach_UnSubscribedActivities(UnSubscribedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Subscriber = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnSubscribedActivity")]
	public partial class UnSubscribedActivity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _UnSubscribedActivityID;
		
		private decimal _SubscriberID;
		
		private bool _SubscribedActivityStatus;
		
		private int _ActivityType;
		
		private string _ActivityName;
		
		private EntityRef<Subscriber> _Subscriber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnSubscribedActivityIDChanging(decimal value);
    partial void OnUnSubscribedActivityIDChanged();
    partial void OnSubscriberIDChanging(decimal value);
    partial void OnSubscriberIDChanged();
    partial void OnSubscribedActivityStatusChanging(bool value);
    partial void OnSubscribedActivityStatusChanged();
    partial void OnActivityTypeChanging(int value);
    partial void OnActivityTypeChanged();
    partial void OnActivityNameChanging(string value);
    partial void OnActivityNameChanged();
    #endregion
		
		public UnSubscribedActivity()
		{
			this._Subscriber = default(EntityRef<Subscriber>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnSubscribedActivityID", AutoSync=AutoSync.OnInsert, DbType="Decimal(19,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal UnSubscribedActivityID
		{
			get
			{
				return this._UnSubscribedActivityID;
			}
			set
			{
				if ((this._UnSubscribedActivityID != value))
				{
					this.OnUnSubscribedActivityIDChanging(value);
					this.SendPropertyChanging();
					this._UnSubscribedActivityID = value;
					this.SendPropertyChanged("UnSubscribedActivityID");
					this.OnUnSubscribedActivityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberID", DbType="Decimal(19,0) NOT NULL")]
		public decimal SubscriberID
		{
			get
			{
				return this._SubscriberID;
			}
			set
			{
				if ((this._SubscriberID != value))
				{
					if (this._Subscriber.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscriberIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberID = value;
					this.SendPropertyChanged("SubscriberID");
					this.OnSubscriberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscribedActivityStatus", DbType="Bit NOT NULL")]
		public bool SubscribedActivityStatus
		{
			get
			{
				return this._SubscribedActivityStatus;
			}
			set
			{
				if ((this._SubscribedActivityStatus != value))
				{
					this.OnSubscribedActivityStatusChanging(value);
					this.SendPropertyChanging();
					this._SubscribedActivityStatus = value;
					this.SendPropertyChanged("SubscribedActivityStatus");
					this.OnSubscribedActivityStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityType", DbType="Int NOT NULL")]
		public int ActivityType
		{
			get
			{
				return this._ActivityType;
			}
			set
			{
				if ((this._ActivityType != value))
				{
					this.OnActivityTypeChanging(value);
					this.SendPropertyChanging();
					this._ActivityType = value;
					this.SendPropertyChanged("ActivityType");
					this.OnActivityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ActivityName
		{
			get
			{
				return this._ActivityName;
			}
			set
			{
				if ((this._ActivityName != value))
				{
					this.OnActivityNameChanging(value);
					this.SendPropertyChanging();
					this._ActivityName = value;
					this.SendPropertyChanged("ActivityName");
					this.OnActivityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscriber_UnSubscribedActivity", Storage="_Subscriber", ThisKey="SubscriberID", OtherKey="SubscriberID", IsForeignKey=true)]
		public Subscriber Subscriber
		{
			get
			{
				return this._Subscriber.Entity;
			}
			set
			{
				Subscriber previousValue = this._Subscriber.Entity;
				if (((previousValue != value) 
							|| (this._Subscriber.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscriber.Entity = null;
						previousValue.UnSubscribedActivities.Remove(this);
					}
					this._Subscriber.Entity = value;
					if ((value != null))
					{
						value.UnSubscribedActivities.Add(this);
						this._SubscriberID = value.SubscriberID;
					}
					else
					{
						this._SubscriberID = default(decimal);
					}
					this.SendPropertyChanged("Subscriber");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
